"""Static project data. Easy to swap for a Django model later."""

PROJECTS = [
    {
        "slug": "creditcheck",
        "title": "CreditCheck Platform",
        "detail_title": "Credit Data Referencing Service",
        "short_description": "Reliable finance & credit data platform providing credit insights, income verification, and identity services for African financial institutions.",
        "image": "creditchek-platform.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "Fintech, Credit Data, B2B",
        "technologies": ["Credit Data", "Fintech", "B2B", "API Platform"],
        "overview": "A reliable finance and credit data platform providing comprehensive credit insights, income verification, and identity services for African financial institutions. The platform enables lenders to make informed credit decisions by aggregating and analyzing financial data from multiple sources.",
        "challenges": [
            "Fragmented credit information across multiple financial institutions in Africa",
            "Lack of standardized credit scoring and assessment tools",
            "Limited access to reliable income verification data",
            "Need for real-time credit decisioning capabilities",
            "Integration challenges with multiple banking systems and data sources",
        ],
        "solutions": [
            "Built comprehensive API platform for credit data aggregation and analysis",
            "Implemented real-time credit scoring and assessment algorithms",
            "Developed income verification services integrated with banking systems",
            "Created identity verification services for enhanced KYC processes",
            "Established secure data exchange protocols with financial institutions",
        ],
        "impact": [
            "Improved credit decisioning accuracy for lending institutions",
            "Reduced loan processing time through automated credit checks",
            "Enhanced financial inclusion by providing comprehensive credit profiles",
            "Enabled better risk assessment for lenders across African markets",
            "Established trusted credit referencing infrastructure for the fintech ecosystem",
        ],
    },
    {
        "slug": "multi-bank-debit",
        "title": "Multi-Bank Direct Debit Solution",
        "detail_title": "Multi-Bank Direct Debit Solution",
        "short_description": "Enterprise direct debit system enabling automated recurring payments across multiple banking institutions with mandate management.",
        "image": "multi-bank-debit.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "Banking, Payment Systems, Enterprise",
        "technologies": ["Direct Debit", "Banking API", "Enterprise", "Payment Systems"],
        "overview": "Enterprise direct debit system enabling automated recurring payments across multiple banking institutions with comprehensive mandate management. The solution streamlines direct debit operations for financial institutions, allowing them to manage customer payment mandates across different banks efficiently.",
        "challenges": [
            "Complex integration requirements across multiple banking institutions",
            "Manual mandate management processes leading to inefficiencies",
            "Lack of standardization in direct debit operations across banks",
            "Difficulty in tracking and managing recurring payment mandates",
            "Need for reliable automated payment collection system",
        ],
        "solutions": [
            "Developed enterprise-grade direct debit platform with multi-bank integration",
            "Implemented automated mandate management and validation system",
            "Created standardized APIs for seamless bank integrations",
            "Built comprehensive dashboard for tracking and managing payment mandates",
            "Established secure payment collection and reconciliation workflows",
        ],
        "impact": [
            "Enabled automated recurring payments across multiple banking institutions",
            "Reduced manual intervention in mandate management and payment collection",
            "Improved payment success rates through reliable automated processes",
            "Enhanced operational efficiency for financial institutions",
            "Positioned as a key component of the Recova lending automation suite",
        ],
    },
    {
        "slug": "recova-redesign",
        "title": "Recova App Suite Redesign",
        "detail_title": "Redesign of Recova App Suite",
        "short_description": "Complete redesign of digital lending platform with enhanced UX/UI, streamlined workflows, and improved credit assessment capabilities.",
        "image": "recova-redesign.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "SaaS, Loan Automation, Fintech",
        "technologies": ["UX/UI Design", "Fintech", "Mobile App", "Web Platform"],
        "overview": "Recova® is an end-to-end lending automation solution built on an advanced technology infrastructure that digitizes the entire loan onboarding lifecycle from customer walk-in/request to credit decisioning, automated disbursement, loan collections and delinquency management. It consists of three applications: Credit Appraisal Solution, Credit Data Referencing, and Multi-bank Direct Debit Solution.",
        "challenges": [
            "Users reported confusion and inefficiency in navigating the existing platform across three different applications",
            "Manual processes in loan onboarding were creating bottlenecks and delays",
            "Lack of cohesive user experience across Credit Appraisal, Data Referencing, and Direct Debit modules",
            "Limited feedback from commercial banks, MFBs, and fintechs on improving the platform's usability",
        ],
        "solutions": [
            "Conducted comprehensive user research sessions with product team and designers to understand pain points and gather feedback",
            "Worked with design agency and business analysts to create a unified design language across all three applications",
            "Implemented streamlined workflows for credit decisioning and automated disbursement",
            "Collaborated with cross-functional teams including product designers across subsidiary companies to align design with user needs",
            "Created weekly implementation reports for senior management and stakeholders to track progress",
        ],
        "impact": [
            "Improved user satisfaction scores across commercial banks, MFBs, and fintech clients",
            "Reduced loan onboarding time through streamlined digital workflows",
            "Created a cohesive user experience that aligned with end-user expectations",
            "Established a scalable design system that could be applied across all Qore products",
            "Enhanced operational efficiency for financial institutions using the platform",
        ],
    },
    {
        "slug": "vendor-management",
        "title": "Leadway Vendor Management Portal",
        "detail_title": "Leadway Vendor Management Portal",
        "short_description": "Vendor onboarding and management portal for Leadway Assurance Company, streamlining vendor registration, document management, and approval workflows.",
        "image": "vendor-management.png",
        "live_url": "https://webapp.leadway.com/vendorformapp",
        "role": "Product Delivery Analyst",
        "company": "Leadway",
        "industry": "Insurance, Enterprise Software",
        "technologies": ["Vendor Management", "Insurance", "B2B", "Portal"],
        "overview": "This project was birthed in a bid to digitalise certain processes in the organisation. Prior to the implementation of this project, vendor registration has always been performed with the use of an excel sheet. However, in a bid to play in the digital space it was necessary the organisation implemented a portal to keep hold of vendors/service provider registration for procurement purpose. The objective of this project was to digitalise the procurement process of service providers in the organisation.",
        "challenges": [
            "Manual vendor registration using Excel sheets was inefficient and error-prone",
            "Lack of centralized system for tracking vendor information and documentation",
            "Difficult to manage procurement processes across multiple departments",
            "Limited visibility into vendor status and approval workflows",
            "No standardized process for vendor onboarding and compliance verification",
        ],
        "solutions": [
            "Managed the team that delivered the development of the vendor management portal",
            "Worked with the technical team to interpret the provided APIs and drew up a comprehensive user flow",
            "Collaborated with the design team to create intuitive UI for the product features",
            "Implemented digital vendor registration and document management system",
            "Created automated approval workflows for vendor onboarding",
        ],
        "impact": [
            "Successfully digitalized the vendor procurement process, eliminating Excel-based workflows",
            "Improved vendor registration efficiency and reduced processing time",
            "Enhanced visibility and tracking of vendor information across the organization",
            "Streamlined approval workflows for faster vendor onboarding",
            "Positioned Leadway for better procurement management and vendor relationship tracking",
        ],
    },
    {
        "slug": "transita",
        "title": "Transita E-commerce Platform",
        "detail_title": "Transita E-Commerce Platform",
        "short_description": "Comprehensive e-commerce solution for transit and logistics companies, featuring booking management, route optimization, and customer portal.",
        "image": "transita-platform.png",
        "live_url": "https://webapp.leadway.com/TransitaApp",
        "role": "Product Manager",
        "company": "Leadway",
        "industry": "E-commerce, Logistics, Transit",
        "technologies": ["E-commerce", "Logistics", "Transit", "B2C"],
        "overview": "Comprehensive e-commerce solution for transit and logistics companies, featuring booking management, route optimization, and customer portal. The platform digitalizes the entire transit booking and management process, making it easier for customers to book trips and for operators to manage their fleet and routes.",
        "challenges": [
            "Manual booking processes leading to inefficiencies and errors",
            "Limited visibility into route availability and scheduling",
            "Difficulty in managing fleet operations and customer bookings",
            "Lack of integrated payment and ticketing system",
            "Need for real-time tracking and customer communication",
        ],
        "solutions": [
            "Developed comprehensive e-commerce platform for transit bookings",
            "Implemented route optimization algorithms for efficient scheduling",
            "Created customer portal for easy booking and trip management",
            "Integrated payment gateway for seamless transactions",
            "Built fleet management system for operators",
        ],
        "impact": [
            "Streamlined booking process for customers and operators",
            "Improved operational efficiency through route optimization",
            "Enhanced customer experience with real-time updates and easy booking",
            "Increased revenue through better capacity utilization",
            "Positioned transit companies for digital transformation",
        ],
    },
    {
        "slug": "hydra-api",
        "title": "Hydra API Gateway",
        "detail_title": "Hydra API Gateway",
        "short_description": "A consolidated API gateway that leverages integration to commercial banks to carry out financial transactions.",
        "image": "7255ba74-4352-4f42-84b0-493ebb9ce6f0.png",
        "live_url": "https://www.hydra.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "SaaS, Enterprise Software, B2B, Fintech",
        "technologies": ["SaaS", "Enterprise Software", "B2B", "Fintech"],
        "overview": "A consolidated API gateway that leverages integration to commercial banks to carry out financial transactions. Hydra provides a unified interface for businesses to access multiple banking services, streamlining payment processing, account management, and financial data aggregation.",
        "challenges": [
            "Fragmented banking APIs across different financial institutions",
            "Complex integration requirements for each bank's unique API",
            "Need for real-time transaction processing and reconciliation",
            "Security and compliance requirements across multiple banking partners",
            "Maintaining uptime and reliability across diverse banking systems",
        ],
        "solutions": [
            "Built unified API gateway abstracting complexity of individual bank APIs",
            "Implemented standardized endpoints for common banking operations",
            "Created real-time transaction processing and monitoring system",
            "Developed comprehensive security layer with encryption and compliance controls",
            "Built fault-tolerant architecture with failover mechanisms",
        ],
        "impact": [
            "Reduced integration time for businesses from months to weeks",
            "Enabled seamless multi-bank operations through single API",
            "Improved transaction success rates through intelligent routing",
            "Established trusted gateway for enterprise financial operations",
            "Scaled to support thousands of daily transactions across multiple banks",
        ],
    },
    {
        "slug": "luna",
        "title": "AI Chatbot & Virtual Reality (Luna)",
        "detail_title": "AI Chatbot & Virtual Reality (Luna)",
        "short_description": "Luna is a conversational chatbot that interacts with customers on behalf of a customer success associate.",
        "image": "1954f087-7966-4d49-928e-758c81f6d217.png",
        "live_url": "",
        "role": "Product Manager",
        "company": "InvestED Inc.",
        "industry": "EdTech, AI/ML",
        "technologies": ["AI/ML", "Virtual Reality", "SaaS", "Enterprise Software"],
        "overview": "Luna is an AI-powered conversational chatbot designed to interact with customers on behalf of customer success associates. Built with advanced natural language processing and virtual reality capabilities, Luna provides personalized, context-aware responses that enhance customer experience while reducing support workload.",
        "challenges": [
            "Creating natural, human-like conversations that could handle complex customer queries across multiple domains",
            "Integrating virtual reality elements to provide immersive customer support experiences",
            "Ensuring the AI maintained brand voice consistency while personalizing responses",
            "Developing a system that could seamlessly escalate to human agents when needed",
            "Training the AI to understand context from previous interactions and customer history",
        ],
        "solutions": [
            "Implemented advanced NLP models trained on thousands of customer interactions to understand intent and context",
            "Developed a hybrid VR/chat interface that allows customers to choose their preferred interaction method",
            "Created a brand voice framework with tone guidelines that the AI references for all responses",
            "Built intelligent escalation triggers that identify when human intervention would be more appropriate",
            "Integrated customer data platform to provide Luna with full context of customer history and preferences",
            "Designed fallback mechanisms and continuous learning loops to improve response quality over time",
        ],
        "impact": [
            "Reduced average customer support response time by 73% through instant AI responses",
            "Achieved 89% customer satisfaction rating for AI-handled interactions",
            "Enabled 24/7 customer support coverage without additional staffing costs",
            "Decreased support ticket volume by 45% by resolving common queries automatically",
            "Improved first-contact resolution rate from 62% to 84%",
            "Generated valuable insights into common customer pain points through conversation analysis",
        ],
    },
    {
        "slug": "leadway-health",
        "title": "Leadway Health Management System",
        "detail_title": "Leadway Health Management System",
        "short_description": "Comprehensive West African Third-Party Administrator for health care needs of insurers and employer groups.",
        "image": "leadway-health-app.png",
        "live_url": "https://leadwayhealth.com",
        "role": "Product Delivery Analyst",
        "company": "Leadway",
        "industry": "Health, Insurance",
        "technologies": ["Health", "Insurance", "Enterprise Software", "B2C"],
        "overview": "Leadway Health Management System is an HMO business and a comprehensive West African Third-Party Administrator, entirely dedicated to servicing proactively the health care needs of insurers, brokers and employer groups across the African continent. The objective of this product is to increase health insurance penetration and access to quality healthcare by providing efficient health care management services and solutions.",
        "challenges": [
            "Traditional HMO workflows were manual, slow, and lacked transparency across brokers, insurers, and care providers",
            "Health insurance adoption was low due to complex access points and limited digital engagement",
            "Claims processing was time-consuming, taking an average of 15 days to resolve",
            "Limited 24/7 access to health services for enrollees and corporate groups",
        ],
        "solutions": [
            "Digitized HMO workflows through integrated web and mobile applications",
            "Implemented API-driven experiences for seamless integration with health providers",
            "Developed mobile-first applications for iOS and Android platforms",
            "Created dedicated portals for corporate organizations and health providers",
            "Built the Prognosis Health Management System for streamlined operations",
        ],
        "impact": [
            "Supported onboarding of 100+ corporate employer groups within the first year",
            "Processed over 300,000 health claims with a claims resolution accuracy of 98.6%",
            "Reduced average claim turnaround time from 15 days to under 5 days via digital processing workflows",
            "Enabled 24/7 access to health services through integrated mobile and web applications",
            "Positioned Leadway as a regional leader in digital health administration, with a scalable model for West African markets",
        ],
    },
    {
        "slug": "agency-banking",
        "title": "Agency Banking Solution (Cluster)",
        "detail_title": "Agency Banking Solution (Cluster)",
        "short_description": "Agent banking solution that enables agents perform banking services via mobile and back-office web applications.",
        "image": "2ddb2bc2-9de0-43d9-8f3f-c80caa96c5ce.png",
        "live_url": "https://web.cluster.africa/logout",
        "role": "Product Manager",
        "company": "Cluster",
        "industry": "Agency Banking, POS, Fintech, B2B",
        "technologies": ["Agency Banking", "POS", "Fintech", "B2B"],
        "overview": "Agent banking solution that enables agents perform banking services via mobile and back-office web applications. The platform empowers agents to offer essential banking services including deposits, withdrawals, transfers, and bill payments, bringing financial services to underserved communities.",
        "challenges": [
            "Limited banking infrastructure in rural and remote areas",
            "Need for reliable offline-capable mobile application",
            "Complex agent onboarding and KYC processes",
            "Transaction reconciliation across multiple agents and locations",
            "Training and support for agents with varying technical expertise",
        ],
        "solutions": [
            "Developed mobile-first agent application with offline capabilities",
            "Built comprehensive back-office web portal for agent management",
            "Implemented streamlined agent onboarding with digital KYC",
            "Created real-time transaction monitoring and reconciliation system",
            "Designed intuitive UI optimized for agents with minimal training",
        ],
        "impact": [
            "Expanded banking access to thousands of underserved communities",
            "Enabled agents to process millions in daily transactions",
            "Reduced transaction costs for end customers",
            "Created new income opportunities for agents across regions",
            "Improved financial inclusion through accessible banking services",
        ],
    },
    {
        "slug": "leadway-superapp",
        "title": "Leadway SuperApp Design",
        "detail_title": "Leadway SuperApp Design",
        "short_description": "Comprehensive SuperApp design for Nigerian financial services conglomerate spanning multiple business areas.",
        "image": "e594e4d5-89f4-4580-aaf8-72ca5ae95dd8.png",
        "live_url": "https://www.figma.com/proto/dV1Xp63mI9T8yZFrKCkmVa/-LW----UI-Concept?page-id=2233%3A30818&node-id=2363-25126&starting-point-node-id=2363%3A25126",
        "role": "Product Designer",
        "company": "Leadway",
        "industry": "Insurance, SaaS, B2C, Design",
        "technologies": ["Insurance", "SaaS", "B2C", "Design"],
        "overview": "Comprehensive SuperApp design for Nigerian financial services conglomerate spanning multiple business areas. The SuperApp consolidates insurance, investment, health services, and other financial products into a unified digital experience, making it easy for customers to manage all their financial needs in one place.",
        "challenges": [
            "Consolidating multiple disparate business units into cohesive experience",
            "Balancing complexity of services with simplicity of user interface",
            "Creating consistent design language across diverse product offerings",
            "Maintaining brand identity while innovating digital experience",
            "Designing for diverse user base with varying digital literacy levels",
        ],
        "solutions": [
            "Designed unified navigation and information architecture",
            "Created comprehensive design system with reusable components",
            "Implemented progressive disclosure to manage complexity",
            "Developed intuitive onboarding flows for each service area",
            "Built responsive design supporting mobile-first approach",
        ],
        "impact": [
            "Unified customer experience across all Leadway services",
            "Improved user engagement through intuitive design",
            "Reduced customer support inquiries with clear UX patterns",
            "Positioned Leadway as digital-first financial services provider",
            "Created scalable design foundation for future product expansion",
        ],
    },
    {
        "slug": "ankara-insurance",
        "title": "Ankara Insurance Portal",
        "detail_title": "Ankara Insurance Portal",
        "short_description": "Third Party Health Administrator (TPHA) digital platform in Cote d'Ivoire enabling users to access health services including health insurance plans, telemedicine, and wellness programs.",
        "image": "ankara-insurance.png",
        "live_url": "",
        "role": "Product Delivery Analyst",
        "company": "Ankara Services (CIV)",
        "industry": "Healthcare, Insurance",
        "technologies": ["Healthcare", "Insurance", "B2C", "Design"],
        "overview": "Ankara is a Third Party Health Administrator (TPHA) born digital in Cote d'Ivoire. Ankara's digital platform enables users to access a wide range of health services and products, including health insurance plans, telemedicine, and wellness programs. The company's mission is to empower individuals to take control of their health and well-being and to make high-quality healthcare more accessible and affordable.",
        "challenges": [
            "Limited access to quality healthcare in Cote d'Ivoire and the West African region",
            "Complex healthcare insurance processes that discouraged adoption",
            "Need to establish a digital-first health administrator brand in a traditional market",
            "Cultural considerations for serving French-speaking stakeholders and users",
            "Creating a comprehensive visual identity and brand from scratch",
        ],
        "solutions": [
            "Designed complete visual identity for the brand including logo and portal interfaces",
            "Created digital platform enabling access to health insurance plans, telemedicine, and wellness programs",
            "Implemented user-friendly interfaces tailored for Cote d'Ivoire market",
            "Developed culturally appropriate design elements after studying French culture",
            "Built comprehensive portals for users to manage their health insurance and services",
        ],
        "impact": [
            "Successfully launched a born-digital TPHA in Cote d'Ivoire",
            "Made high-quality healthcare more accessible and affordable in the region",
            "Empowered individuals to take control of their health through digital tools",
            "Established strong brand identity that resonated with local market",
            "Positioned Ankara for expansion across West Africa with scalable digital platform",
        ],
    },
    {
        "slug": "leadway-investment",
        "title": "Leadway Micro Investment Portal",
        "detail_title": "Leadway Micro Investment Portal",
        "short_description": "Investment platform that makes investing simple and accessible with cutting-edge tools, expert guidance and user-friendly interface. Features multi-currency investment options in naira or dollars.",
        "image": "leadway-investment.png",
        "live_url": "",
        "role": "Product Delivery Analyst",
        "company": "Leadway Asset Management",
        "industry": "Finance, Investment",
        "technologies": ["Finance", "Investment", "B2C", "Web Platform"],
        "overview": "A webapp that makes investing simple and accessible to all, with its cutting-edge tools, expert guidance and user-friendly interface. Whether investing to edge inflation or for any other reason, the portal gives users the confidence to make smart investment decisions and grow their wealth. With the Leadway Investment Portal, investors have a one-stop shop for managing their investments and reaching their financial goals.",
        "challenges": [
            "Limited investment accessibility for retail investors in Nigeria",
            "Complex investment processes deterring new investors",
            "Need for multi-currency investment options (Naira and Dollar) to hedge against inflation",
            "Lack of user-friendly platform for micro-investments",
            "Limited financial literacy and investment guidance for retail users",
        ],
        "solutions": [
            "Developed user-friendly web portal with intuitive investment management interface",
            "Implemented multi-currency investment options allowing users to invest in both Naira and Dollars",
            "Created cutting-edge tools for portfolio management and tracking",
            "Integrated expert guidance features to help users make informed decisions",
            "Designed streamlined investment workflows from registration to portfolio management",
        ],
        "impact": [
            "Made investing accessible to retail investors with varying budget sizes",
            "Enabled users to hedge against inflation through multi-currency investment options",
            "Provided competitive ROIs for both Naira and Dollar investments",
            "Simplified investment decisions through expert guidance and user-friendly interface",
            "Positioned Leadway Asset Management as a leader in digital micro-investment solutions",
        ],
    },
    {
        "slug": "handyman-ops-desk",
        "title": "Handyman Ops Desk (n8n Multi-Agent)",
        "detail_title": "Handyman Ops Desk — n8n Multi-Agent Business Workflow",
        "short_description": "A multi-agent business workflow built in n8n Cloud that intakes handyman service requests from a Google Form, extracts structured job data with Gemini, prices the job, proposes time slots, and emails differentiated client/operations confirmations.",
        "image": "handyman-n8n.png",
        "live_url": "",
        "role": "Student",
        "company": "Baylor University",
        "industry": "Workflow Automation, AI Agents, Operations",
        "technologies": ["n8n", "Google Gemini", "JavaScript", "Google Sheets", "Gmail API", "Webhooks"],
        "overview": "Handyman Ops Desk is a no-code/low-code multi-agent workflow built in n8n Cloud that automates the front-office of a handyman business. A customer submits a service request through a Google Form; an Orchestrator workflow then coordinates four specialized agent workflows — Intake (Gemini-powered structured extraction), Pricing (rules-based JavaScript estimator with zip-aware travel and rush-fee logic), Scheduling (live time API + slot selector that respects customer day preferences), and Comms (Gemini-drafted confirmation message) — and emails differentiated confirmations to the client and operations team based on job urgency and estimate size.",
        "challenges": [
            "Coordinating four independent agent workflows over HTTP while preserving job, pricing, and scheduling context across each step",
            "Forcing Gemini to return strictly valid JSON — the model often wrapped responses in markdown code fences (```json ... ```), breaking downstream parsing",
            "Handling n8n quirks where embedded {{ }} expressions inside literal JSON in Respond-to-Webhook nodes failed validation",
            "Routing high-priority or high-value jobs (urgency = high OR estimate > $300) to operations while normal jobs go straight to client confirmation",
            "Normalizing inconsistent free-text address fields into structured address, unit, and zip components",
        ],
        "solutions": [
            "Designed an Orchestrator workflow that calls four sub-agent webhooks in sequence, using Set nodes (Store Job, Store Pricing, Store Scheduling) and Merge nodes to carry context forward between steps",
            "Added strict JSON-only system prompts to every Gemini node and a JavaScript Clean JSON node that strips markdown fences before JSON.parse, with a clear error message preserving the raw output for debugging",
            "Switched Respond-to-Webhook nodes to Expression mode (or Text + JSON.stringify with application/json content-type) to avoid literal-JSON validation errors",
            "Built rules-based pricing in JavaScript: catalog lookup by service, zip-based travel cost (76706 = $0, 76708 = $10, else $20), and a 20% rush surcharge for high-urgency jobs",
            "Implemented an IF node that branches on urgency or estimate threshold, routing to a Comms (Operations) path or Comms (Client) path with separate Gmail templates for each audience",
            "Used Google Sheets Trigger (rowAdded) on a public Google Form response sheet so new customer requests automatically kick off the workflow with no manual intervention",
        ],
        "impact": [
            "Demonstrated a working agentic-orchestration pattern (one orchestrator, four specialized agents) entirely in a no-code GUI, with each agent independently activatable and testable via its own Production webhook",
            "Reduced a manual triage workflow (read request → estimate → schedule → reply) into a single form submission that produces a fully-drafted customer email and an operations alert",
            "Captured reusable n8n + Gemini integration patterns — JSON-only prompting, fence-stripping cleanup, and HTTP-body object passing — that generalize to any LLM-in-workflow project",
            "Showed how rule-based deterministic logic (pricing, slot filtering) can be cleanly composed alongside generative AI (intake parsing, message drafting) in the same pipeline",
            "Delivered a complete end-to-end business automation as a graduate-coursework mid-term project, from form ingestion to differentiated client and operations email outputs",
        ],
    },
    {
        "slug": "shift",
        "title": "Shift — Volunteer Marketplace (WACODE Hackathon)",
        "detail_title": "Shift — Volunteer Marketplace (WACODE 2026 Hackathon)",
        "short_description": "Two-sided volunteer marketplace — 'the DoorDash for volunteering' — built in 24 hours and placed 4th at WACODE 2026 (Baylor University). Nonprofits publish shifts; students browse a ranked feed, claim in two taps, and join a smart waitlist with automated promotion.",
        "image": "shift-cover.png",
        "live_url": "https://shiftbear-five.vercel.app",
        "role": "Product Manager & Co-Builder",
        "company": "WACODE 2026 — Baylor University",
        "industry": "Hackathon, Social Good, Two-Sided Marketplace",
        "technologies": ["Next.js 16", "TypeScript", "React 19", "Tailwind v4", "PostgreSQL (Neon)", "Resend", "Magic-Link Auth", "Vercel", "Remotion"],
        "overview": "Shift is a two-sided volunteer marketplace — 'the DoorDash for volunteering' — that connects nonprofits with student volunteers who need flexible, nearby ways to give back. Nonprofits publish shifts with time, location, and capacity; students browse a personalized feed ranked for their schedule and proximity, claim slots in two taps, and join a smart waitlist that auto-promotes the next person (with a 30-minute confirmation window) when someone drops. Built in 24 hours for WACODE 2026 at Baylor University by a team of two — Ayokunmi Sodamola (PM & co-builder) and Kolade Abobarin (co-builder) — where it placed 4th.",
        "challenges": [
            "Scoping a real two-sided marketplace (nonprofit admin flows + student claim flows + email + cron + auth) tight enough to actually ship end-to-end in a 24-hour window",
            "Avoiding the 'fake auth' shortcut — we wanted real magic-link authentication with hashed tokens and HTTP-only session cookies, not a mocked login for the demo",
            "Handling waitlist race conditions atomically — when a slot opens, two students could hit the promotion endpoint simultaneously and double-book the spot",
            "Working around Vercel Hobby's lack of scheduled cron — the waitlist expiry and 2-hour reminder jobs couldn't run on a timer on free tier, but needed to exist for the product to work",
            "Serving two very different audiences (students on phones claiming shifts; nonprofit admins on laptops publishing and tracking attendance) from one codebase without fragmenting into two apps",
            "Producing a compelling 60-second demo video for judging in the final hour without any traditional video tooling or editing experience",
        ],
        "solutions": [
            "Built on Next.js 16 App Router with React Server Components and Tailwind v4, giving us a single design system across student and admin UIs and fast shipping velocity",
            "Used postgres.js tagged-template SQL against Neon Postgres, wrapping claim and waitlist operations in sql.begin() transactions to atomically serialize state changes and prevent double-booking",
            "Built real magic-link auth: token hashing at rest, HTTP-only session cookies, and a proxy.ts request-level middleware gating /student and /admin routes — no client-stored JWTs, no mocked sessions",
            "Integrated Resend for transactional email (claim confirmations, waitlist promotions, 2-hour reminders) with an email_log table for idempotency so retries never double-send",
            "Stubbed the scheduled cron job in vercel.json with a documented upgrade path to Vercel Pro (/api/cron/run every 5 minutes); kept it manually invokable via curl with a bearer secret so judges could trigger waitlist expiry live",
            "Designed a single codebase with cleanly separated /student/* and /admin/* route trees sharing the auth and DB layers — one deployment, two experiences",
            "Generated the entire promo video in Remotion + Claude Code in under 60 minutes — React-coded animations with Claude iterating the slide copy and styling in a tight feedback loop — and published alongside the build to LinkedIn",
        ],
        "impact": [
            "Placed 4th at WACODE 2026 (24-hour hackathon, Baylor University, theme: 'technology for social good')",
            "Shipped a production-ready two-sided marketplace — not a hackathon prototype — with real auth, transactional database, transactional email, and a documented path to scheduled cron",
            "Tackled a real community problem in Waco, TX: reduced friction for local nonprofits (Meals on Wheels, Mission Waco) to recruit and for students to volunteer on their actual schedules",
            "Released a Remotion + Claude Code demo-video workflow that resonated with the tech community on LinkedIn (31 reactions, 7 comments) — reframing creative work as a code problem",
            "Live and publicly usable at shiftbear-five.vercel.app; code open-sourced at github.com/Bobarinn/ShiftBear",
        ],
    },
]

PROJECTS_BY_SLUG = {p["slug"]: p for p in PROJECTS}
