"""Seed data for the Project model.

Imported by main/migrations/0002_seed_initial_data.py on first migrate.
After the database is seeded, the live site reads from main.models.Project
(see main/views.py), not from this module. Edit projects via Django admin
(/admin/main/project/) for ongoing changes.
"""

PROJECTS = [
    {
        "slug": "creditcheck",
        "title": "CreditCheck Platform",
        "detail_title": "Credit Data Referencing Service",
        "short_description": "Reliable finance & credit data platform providing credit insights, income verification, and identity services for African financial institutions.",
        "image": "creditchek-platform.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "Fintech, Credit Data, B2B",
        "technologies": ["Credit Data", "Fintech", "B2B", "API Platform"],
        "overview": "A reliable finance and credit data platform providing comprehensive credit insights, income verification, and identity services for African financial institutions. The platform enables lenders to make informed credit decisions by aggregating and analyzing financial data from multiple sources.",
        "challenges": [
            "Fragmented credit information across multiple financial institutions in Africa",
            "Lack of standardized credit scoring and assessment tools",
            "Limited access to reliable income verification data",
            "Need for real-time credit decisioning capabilities",
            "Integration challenges with multiple banking systems and data sources",
        ],
        "solutions": [
            "Built comprehensive API platform for credit data aggregation and analysis",
            "Implemented real-time credit scoring and assessment algorithms",
            "Developed income verification services integrated with banking systems",
            "Created identity verification services for enhanced KYC processes",
            "Established secure data exchange protocols with financial institutions",
        ],
        "impact": [
            "Improved credit decisioning accuracy for lending institutions",
            "Reduced loan processing time through automated credit checks",
            "Enhanced financial inclusion by providing comprehensive credit profiles",
            "Enabled better risk assessment for lenders across African markets",
            "Established trusted credit referencing infrastructure for the fintech ecosystem",
        ],
    },
    {
        "slug": "multi-bank-debit",
        "title": "Multi-Bank Direct Debit Solution",
        "detail_title": "Multi-Bank Direct Debit Solution",
        "short_description": "Enterprise direct debit system enabling automated recurring payments across multiple banking institutions with mandate management.",
        "image": "multi-bank-debit.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "Banking, Payment Systems, Enterprise",
        "technologies": ["Direct Debit", "Banking API", "Enterprise", "Payment Systems"],
        "overview": "Enterprise direct debit system enabling automated recurring payments across multiple banking institutions with comprehensive mandate management. The solution streamlines direct debit operations for financial institutions, allowing them to manage customer payment mandates across different banks efficiently.",
        "challenges": [
            "Complex integration requirements across multiple banking institutions",
            "Manual mandate management processes leading to inefficiencies",
            "Lack of standardization in direct debit operations across banks",
            "Difficulty in tracking and managing recurring payment mandates",
            "Need for reliable automated payment collection system",
        ],
        "solutions": [
            "Developed enterprise-grade direct debit platform with multi-bank integration",
            "Implemented automated mandate management and validation system",
            "Created standardized APIs for seamless bank integrations",
            "Built comprehensive dashboard for tracking and managing payment mandates",
            "Established secure payment collection and reconciliation workflows",
        ],
        "impact": [
            "Enabled automated recurring payments across multiple banking institutions",
            "Reduced manual intervention in mandate management and payment collection",
            "Improved payment success rates through reliable automated processes",
            "Enhanced operational efficiency for financial institutions",
            "Positioned as a key component of the Recova lending automation suite",
        ],
    },
    {
        "slug": "recova-redesign",
        "title": "Recova App Suite Redesign",
        "detail_title": "Redesign of Recova App Suite",
        "short_description": "Complete redesign of digital lending platform with enhanced UX/UI, streamlined workflows, and improved credit assessment capabilities.",
        "image": "recova-redesign.png",
        "live_url": "https://web.recova.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "SaaS, Loan Automation, Fintech",
        "technologies": ["UX/UI Design", "Fintech", "Mobile App", "Web Platform"],
        "overview": "Recova® is an end-to-end lending automation solution built on an advanced technology infrastructure that digitizes the entire loan onboarding lifecycle from customer walk-in/request to credit decisioning, automated disbursement, loan collections and delinquency management. It consists of three applications: Credit Appraisal Solution, Credit Data Referencing, and Multi-bank Direct Debit Solution.",
        "challenges": [
            "Users reported confusion and inefficiency in navigating the existing platform across three different applications",
            "Manual processes in loan onboarding were creating bottlenecks and delays",
            "Lack of cohesive user experience across Credit Appraisal, Data Referencing, and Direct Debit modules",
            "Limited feedback from commercial banks, MFBs, and fintechs on improving the platform's usability",
        ],
        "solutions": [
            "Conducted comprehensive user research sessions with product team and designers to understand pain points and gather feedback",
            "Worked with design agency and business analysts to create a unified design language across all three applications",
            "Implemented streamlined workflows for credit decisioning and automated disbursement",
            "Collaborated with cross-functional teams including product designers across subsidiary companies to align design with user needs",
            "Created weekly implementation reports for senior management and stakeholders to track progress",
        ],
        "impact": [
            "Improved user satisfaction scores across commercial banks, MFBs, and fintech clients",
            "Reduced loan onboarding time through streamlined digital workflows",
            "Created a cohesive user experience that aligned with end-user expectations",
            "Established a scalable design system that could be applied across all Qore products",
            "Enhanced operational efficiency for financial institutions using the platform",
        ],
    },
    {
        "slug": "vendor-management",
        "title": "Leadway Vendor Management Portal",
        "detail_title": "Leadway Vendor Management Portal",
        "short_description": "Vendor onboarding and management portal for Leadway Assurance Company, streamlining vendor registration, document management, and approval workflows.",
        "image": "vendor-management.png",
        "live_url": "https://webapp.leadway.com/vendorformapp",
        "role": "Product Delivery Analyst",
        "company": "Leadway",
        "industry": "Insurance, Enterprise Software",
        "technologies": ["Vendor Management", "Insurance", "B2B", "Portal"],
        "overview": "This project was birthed in a bid to digitalise certain processes in the organisation. Prior to the implementation of this project, vendor registration has always been performed with the use of an excel sheet. However, in a bid to play in the digital space it was necessary the organisation implemented a portal to keep hold of vendors/service provider registration for procurement purpose. The objective of this project was to digitalise the procurement process of service providers in the organisation.",
        "challenges": [
            "Manual vendor registration using Excel sheets was inefficient and error-prone",
            "Lack of centralized system for tracking vendor information and documentation",
            "Difficult to manage procurement processes across multiple departments",
            "Limited visibility into vendor status and approval workflows",
            "No standardized process for vendor onboarding and compliance verification",
        ],
        "solutions": [
            "Managed the team that delivered the development of the vendor management portal",
            "Worked with the technical team to interpret the provided APIs and drew up a comprehensive user flow",
            "Collaborated with the design team to create intuitive UI for the product features",
            "Implemented digital vendor registration and document management system",
            "Created automated approval workflows for vendor onboarding",
        ],
        "impact": [
            "Successfully digitalized the vendor procurement process, eliminating Excel-based workflows",
            "Improved vendor registration efficiency and reduced processing time",
            "Enhanced visibility and tracking of vendor information across the organization",
            "Streamlined approval workflows for faster vendor onboarding",
            "Positioned Leadway for better procurement management and vendor relationship tracking",
        ],
    },
    {
        "slug": "transita",
        "title": "Transita E-commerce Platform",
        "detail_title": "Transita E-Commerce Platform",
        "short_description": "Comprehensive e-commerce solution for transit and logistics companies, featuring booking management, route optimization, and customer portal.",
        "image": "transita-platform.png",
        "live_url": "https://webapp.leadway.com/TransitaApp",
        "role": "Product Manager",
        "company": "Leadway",
        "industry": "E-commerce, Logistics, Transit",
        "technologies": ["E-commerce", "Logistics", "Transit", "B2C"],
        "overview": "Comprehensive e-commerce solution for transit and logistics companies, featuring booking management, route optimization, and customer portal. The platform digitalizes the entire transit booking and management process, making it easier for customers to book trips and for operators to manage their fleet and routes.",
        "challenges": [
            "Manual booking processes leading to inefficiencies and errors",
            "Limited visibility into route availability and scheduling",
            "Difficulty in managing fleet operations and customer bookings",
            "Lack of integrated payment and ticketing system",
            "Need for real-time tracking and customer communication",
        ],
        "solutions": [
            "Developed comprehensive e-commerce platform for transit bookings",
            "Implemented route optimization algorithms for efficient scheduling",
            "Created customer portal for easy booking and trip management",
            "Integrated payment gateway for seamless transactions",
            "Built fleet management system for operators",
        ],
        "impact": [
            "Streamlined booking process for customers and operators",
            "Improved operational efficiency through route optimization",
            "Enhanced customer experience with real-time updates and easy booking",
            "Increased revenue through better capacity utilization",
            "Positioned transit companies for digital transformation",
        ],
    },
    {
        "slug": "hydra-api",
        "title": "Hydra API Gateway",
        "detail_title": "Hydra API Gateway",
        "short_description": "A consolidated API gateway that leverages integration to commercial banks to carry out financial transactions.",
        "image": "7255ba74-4352-4f42-84b0-493ebb9ce6f0.png",
        "live_url": "https://www.hydra.ng",
        "role": "Product Manager",
        "company": "Qore",
        "industry": "SaaS, Enterprise Software, B2B, Fintech",
        "technologies": ["SaaS", "Enterprise Software", "B2B", "Fintech"],
        "overview": "A consolidated API gateway that leverages integration to commercial banks to carry out financial transactions. Hydra provides a unified interface for businesses to access multiple banking services, streamlining payment processing, account management, and financial data aggregation.",
        "challenges": [
            "Fragmented banking APIs across different financial institutions",
            "Complex integration requirements for each bank's unique API",
            "Need for real-time transaction processing and reconciliation",
            "Security and compliance requirements across multiple banking partners",
            "Maintaining uptime and reliability across diverse banking systems",
        ],
        "solutions": [
            "Built unified API gateway abstracting complexity of individual bank APIs",
            "Implemented standardized endpoints for common banking operations",
            "Created real-time transaction processing and monitoring system",
            "Developed comprehensive security layer with encryption and compliance controls",
            "Built fault-tolerant architecture with failover mechanisms",
        ],
        "impact": [
            "Reduced integration time for businesses from months to weeks",
            "Enabled seamless multi-bank operations through single API",
            "Improved transaction success rates through intelligent routing",
            "Established trusted gateway for enterprise financial operations",
            "Scaled to support thousands of daily transactions across multiple banks",
        ],
    },
    {
        "slug": "luna",
        "title": "AI Chatbot & Virtual Reality (Luna)",
        "detail_title": "AI Chatbot & Virtual Reality (Luna)",
        "short_description": "Luna is a conversational chatbot that interacts with customers on behalf of a customer success associate.",
        "image": "1954f087-7966-4d49-928e-758c81f6d217.png",
        "live_url": "",
        "role": "Product Manager",
        "company": "InvestED Inc.",
        "industry": "EdTech, AI/ML",
        "technologies": ["AI/ML", "Virtual Reality", "SaaS", "Enterprise Software"],
        "overview": "Luna is an AI-powered conversational chatbot designed to interact with customers on behalf of customer success associates. Built with advanced natural language processing and virtual reality capabilities, Luna provides personalized, context-aware responses that enhance customer experience while reducing support workload.",
        "challenges": [
            "Creating natural, human-like conversations that could handle complex customer queries across multiple domains",
            "Integrating virtual reality elements to provide immersive customer support experiences",
            "Ensuring the AI maintained brand voice consistency while personalizing responses",
            "Developing a system that could seamlessly escalate to human agents when needed",
            "Training the AI to understand context from previous interactions and customer history",
        ],
        "solutions": [
            "Implemented advanced NLP models trained on thousands of customer interactions to understand intent and context",
            "Developed a hybrid VR/chat interface that allows customers to choose their preferred interaction method",
            "Created a brand voice framework with tone guidelines that the AI references for all responses",
            "Built intelligent escalation triggers that identify when human intervention would be more appropriate",
            "Integrated customer data platform to provide Luna with full context of customer history and preferences",
            "Designed fallback mechanisms and continuous learning loops to improve response quality over time",
        ],
        "impact": [
            "Reduced average customer support response time by 73% through instant AI responses",
            "Achieved 89% customer satisfaction rating for AI-handled interactions",
            "Enabled 24/7 customer support coverage without additional staffing costs",
            "Decreased support ticket volume by 45% by resolving common queries automatically",
            "Improved first-contact resolution rate from 62% to 84%",
            "Generated valuable insights into common customer pain points through conversation analysis",
        ],
    },
    {
        "slug": "leadway-health",
        "title": "Leadway Health Management System",
        "detail_title": "Leadway Health Management System",
        "short_description": "Comprehensive West African Third-Party Administrator for health care needs of insurers and employer groups.",
        "image": "leadway-health-app.png",
        "live_url": "https://leadwayhealth.com",
        "role": "Product Delivery Analyst",
        "company": "Leadway",
        "industry": "Health, Insurance",
        "technologies": ["Health", "Insurance", "Enterprise Software", "B2C"],
        "overview": "Leadway Health Management System is an HMO business and a comprehensive West African Third-Party Administrator, entirely dedicated to servicing proactively the health care needs of insurers, brokers and employer groups across the African continent. The objective of this product is to increase health insurance penetration and access to quality healthcare by providing efficient health care management services and solutions.",
        "challenges": [
            "Traditional HMO workflows were manual, slow, and lacked transparency across brokers, insurers, and care providers",
            "Health insurance adoption was low due to complex access points and limited digital engagement",
            "Claims processing was time-consuming, taking an average of 15 days to resolve",
            "Limited 24/7 access to health services for enrollees and corporate groups",
        ],
        "solutions": [
            "Digitized HMO workflows through integrated web and mobile applications",
            "Implemented API-driven experiences for seamless integration with health providers",
            "Developed mobile-first applications for iOS and Android platforms",
            "Created dedicated portals for corporate organizations and health providers",
            "Built the Prognosis Health Management System for streamlined operations",
        ],
        "impact": [
            "Supported onboarding of 100+ corporate employer groups within the first year",
            "Processed over 300,000 health claims with a claims resolution accuracy of 98.6%",
            "Reduced average claim turnaround time from 15 days to under 5 days via digital processing workflows",
            "Enabled 24/7 access to health services through integrated mobile and web applications",
            "Positioned Leadway as a regional leader in digital health administration, with a scalable model for West African markets",
        ],
    },
    {
        "slug": "agency-banking",
        "title": "Agency Banking Solution (Cluster)",
        "detail_title": "Agency Banking Solution (Cluster)",
        "short_description": "Agent banking solution that enables agents perform banking services via mobile and back-office web applications.",
        "image": "2ddb2bc2-9de0-43d9-8f3f-c80caa96c5ce.png",
        "live_url": "https://web.cluster.africa/logout",
        "role": "Product Manager",
        "company": "Cluster",
        "industry": "Agency Banking, POS, Fintech, B2B",
        "technologies": ["Agency Banking", "POS", "Fintech", "B2B"],
        "overview": "Agent banking solution that enables agents perform banking services via mobile and back-office web applications. The platform empowers agents to offer essential banking services including deposits, withdrawals, transfers, and bill payments, bringing financial services to underserved communities.",
        "challenges": [
            "Limited banking infrastructure in rural and remote areas",
            "Need for reliable offline-capable mobile application",
            "Complex agent onboarding and KYC processes",
            "Transaction reconciliation across multiple agents and locations",
            "Training and support for agents with varying technical expertise",
        ],
        "solutions": [
            "Developed mobile-first agent application with offline capabilities",
            "Built comprehensive back-office web portal for agent management",
            "Implemented streamlined agent onboarding with digital KYC",
            "Created real-time transaction monitoring and reconciliation system",
            "Designed intuitive UI optimized for agents with minimal training",
        ],
        "impact": [
            "Expanded banking access to thousands of underserved communities",
            "Enabled agents to process millions in daily transactions",
            "Reduced transaction costs for end customers",
            "Created new income opportunities for agents across regions",
            "Improved financial inclusion through accessible banking services",
        ],
    },
    {
        "slug": "leadway-superapp",
        "title": "Leadway SuperApp Design",
        "detail_title": "Leadway SuperApp Design",
        "short_description": "Comprehensive SuperApp design for Nigerian financial services conglomerate spanning multiple business areas.",
        "image": "e594e4d5-89f4-4580-aaf8-72ca5ae95dd8.png",
        "live_url": "https://www.figma.com/proto/dV1Xp63mI9T8yZFrKCkmVa/-LW----UI-Concept?page-id=2233%3A30818&node-id=2363-25126&starting-point-node-id=2363%3A25126",
        "role": "Product Designer",
        "company": "Leadway",
        "industry": "Insurance, SaaS, B2C, Design",
        "technologies": ["Insurance", "SaaS", "B2C", "Design"],
        "overview": "Comprehensive SuperApp design for Nigerian financial services conglomerate spanning multiple business areas. The SuperApp consolidates insurance, investment, health services, and other financial products into a unified digital experience, making it easy for customers to manage all their financial needs in one place.",
        "challenges": [
            "Consolidating multiple disparate business units into cohesive experience",
            "Balancing complexity of services with simplicity of user interface",
            "Creating consistent design language across diverse product offerings",
            "Maintaining brand identity while innovating digital experience",
            "Designing for diverse user base with varying digital literacy levels",
        ],
        "solutions": [
            "Designed unified navigation and information architecture",
            "Created comprehensive design system with reusable components",
            "Implemented progressive disclosure to manage complexity",
            "Developed intuitive onboarding flows for each service area",
            "Built responsive design supporting mobile-first approach",
        ],
        "impact": [
            "Unified customer experience across all Leadway services",
            "Improved user engagement through intuitive design",
            "Reduced customer support inquiries with clear UX patterns",
            "Positioned Leadway as digital-first financial services provider",
            "Created scalable design foundation for future product expansion",
        ],
    },
    {
        "slug": "ankara-insurance",
        "title": "Ankara Insurance Portal",
        "detail_title": "Ankara Insurance Portal",
        "short_description": "Third Party Health Administrator (TPHA) digital platform in Cote d'Ivoire enabling users to access health services including health insurance plans, telemedicine, and wellness programs.",
        "image": "ankara-insurance.png",
        "live_url": "",
        "role": "Product Delivery Analyst",
        "company": "Ankara Services (CIV)",
        "industry": "Healthcare, Insurance",
        "technologies": ["Healthcare", "Insurance", "B2C", "Design"],
        "overview": "Ankara is a Third Party Health Administrator (TPHA) born digital in Cote d'Ivoire. Ankara's digital platform enables users to access a wide range of health services and products, including health insurance plans, telemedicine, and wellness programs. The company's mission is to empower individuals to take control of their health and well-being and to make high-quality healthcare more accessible and affordable.",
        "challenges": [
            "Limited access to quality healthcare in Cote d'Ivoire and the West African region",
            "Complex healthcare insurance processes that discouraged adoption",
            "Need to establish a digital-first health administrator brand in a traditional market",
            "Cultural considerations for serving French-speaking stakeholders and users",
            "Creating a comprehensive visual identity and brand from scratch",
        ],
        "solutions": [
            "Designed complete visual identity for the brand including logo and portal interfaces",
            "Created digital platform enabling access to health insurance plans, telemedicine, and wellness programs",
            "Implemented user-friendly interfaces tailored for Cote d'Ivoire market",
            "Developed culturally appropriate design elements after studying French culture",
            "Built comprehensive portals for users to manage their health insurance and services",
        ],
        "impact": [
            "Successfully launched a born-digital TPHA in Cote d'Ivoire",
            "Made high-quality healthcare more accessible and affordable in the region",
            "Empowered individuals to take control of their health through digital tools",
            "Established strong brand identity that resonated with local market",
            "Positioned Ankara for expansion across West Africa with scalable digital platform",
        ],
    },
    {
        "slug": "leadway-investment",
        "title": "Leadway Micro Investment Portal",
        "detail_title": "Leadway Micro Investment Portal",
        "short_description": "Investment platform that makes investing simple and accessible with cutting-edge tools, expert guidance and user-friendly interface. Features multi-currency investment options in naira or dollars.",
        "image": "leadway-investment.png",
        "live_url": "",
        "role": "Product Delivery Analyst",
        "company": "Leadway Asset Management",
        "industry": "Finance, Investment",
        "technologies": ["Finance", "Investment", "B2C", "Web Platform"],
        "overview": "A webapp that makes investing simple and accessible to all, with its cutting-edge tools, expert guidance and user-friendly interface. Whether investing to edge inflation or for any other reason, the portal gives users the confidence to make smart investment decisions and grow their wealth. With the Leadway Investment Portal, investors have a one-stop shop for managing their investments and reaching their financial goals.",
        "challenges": [
            "Limited investment accessibility for retail investors in Nigeria",
            "Complex investment processes deterring new investors",
            "Need for multi-currency investment options (Naira and Dollar) to hedge against inflation",
            "Lack of user-friendly platform for micro-investments",
            "Limited financial literacy and investment guidance for retail users",
        ],
        "solutions": [
            "Developed user-friendly web portal with intuitive investment management interface",
            "Implemented multi-currency investment options allowing users to invest in both Naira and Dollars",
            "Created cutting-edge tools for portfolio management and tracking",
            "Integrated expert guidance features to help users make informed decisions",
            "Designed streamlined investment workflows from registration to portfolio management",
        ],
        "impact": [
            "Made investing accessible to retail investors with varying budget sizes",
            "Enabled users to hedge against inflation through multi-currency investment options",
            "Provided competitive ROIs for both Naira and Dollar investments",
            "Simplified investment decisions through expert guidance and user-friendly interface",
            "Positioned Leadway Asset Management as a leader in digital micro-investment solutions",
        ],
    },
    {
        "slug": "shift",
        "title": "Shift - Volunteer Marketplace",
        "detail_title": "Shift - Volunteer Marketplace (WACODE 2026 Hackathon)",
        "short_description": "Two-sided volunteer marketplace - 'the DoorDash for volunteering' - built in 24 hours and placed 4th at WACODE 2026 (Baylor University). Nonprofits publish shifts; students browse a ranked feed, claim in two taps, and join a smart waitlist with automated promotion.",
        "image": "shift-cover.png",
        "live_url": "https://shiftbear-five.vercel.app",
        "role": "Product Manager & Co-Builder",
        "company": "WACODE 2026 - Baylor University",
        "industry": "Hackathon, Social Good, Two-Sided Marketplace",
        "technologies": ["Next.js 16", "TypeScript", "React 19", "Tailwind v4", "PostgreSQL (Neon)", "Resend", "Magic-Link Auth", "Vercel", "Remotion"],
        "overview": "Shift is a two-sided volunteer marketplace - 'the DoorDash for volunteering' - that connects nonprofits with student volunteers who need flexible, nearby ways to give back. Nonprofits publish shifts with time, location, and capacity; students browse a personalized feed ranked for their schedule and proximity, claim slots in two taps, and join a smart waitlist that auto-promotes the next person (with a 30-minute confirmation window) when someone drops. Built in 24 hours for WACODE 2026 at Baylor University by a team of two - Ayokunmi Sodamola (PM & co-builder) and Kolade Abobarin (co-builder) - where it placed 4th.",
        "challenges": [
            "Scoping a real two-sided marketplace (nonprofit admin flows + student claim flows + email + cron + auth) tight enough to actually ship end-to-end in a 24-hour window",
            "Avoiding the 'fake auth' shortcut - we wanted real magic-link authentication with hashed tokens and HTTP-only session cookies, not a mocked login for the demo",
            "Handling waitlist race conditions atomically - when a slot opens, two students could hit the promotion endpoint simultaneously and double-book the spot",
            "Working around Vercel Hobby's lack of scheduled cron - the waitlist expiry and 2-hour reminder jobs couldn't run on a timer on free tier, but needed to exist for the product to work",
            "Serving two very different audiences (students on phones claiming shifts; nonprofit admins on laptops publishing and tracking attendance) from one codebase without fragmenting into two apps",
            "Producing a compelling 60-second demo video for judging in the final hour without any traditional video tooling or editing experience",
        ],
        "solutions": [
            "Built on Next.js 16 App Router with React Server Components and Tailwind v4, giving us a single design system across student and admin UIs and fast shipping velocity",
            "Used postgres.js tagged-template SQL against Neon Postgres, wrapping claim and waitlist operations in sql.begin() transactions to atomically serialize state changes and prevent double-booking",
            "Built real magic-link auth: token hashing at rest, HTTP-only session cookies, and a proxy.ts request-level middleware gating /student and /admin routes - no client-stored JWTs, no mocked sessions",
            "Integrated Resend for transactional email (claim confirmations, waitlist promotions, 2-hour reminders) with an email_log table for idempotency so retries never double-send",
            "Stubbed the scheduled cron job in vercel.json with a documented upgrade path to Vercel Pro (/api/cron/run every 5 minutes); kept it manually invokable via curl with a bearer secret so judges could trigger waitlist expiry live",
            "Designed a single codebase with cleanly separated /student/* and /admin/* route trees sharing the auth and DB layers - one deployment, two experiences",
            "Generated the entire promo video in Remotion + Claude Code in under 60 minutes - React-coded animations with Claude iterating the slide copy and styling in a tight feedback loop - and published alongside the build to LinkedIn",
        ],
        "impact": [
            "Placed 4th at WACODE 2026 (24-hour hackathon, Baylor University, theme: 'technology for social good')",
            "Shipped a production-ready two-sided marketplace - not a hackathon prototype - with real auth, transactional database, transactional email, and a documented path to scheduled cron",
            "Tackled a real community problem in Waco, TX: reduced friction for local nonprofits (Meals on Wheels, Mission Waco) to recruit and for students to volunteer on their actual schedules",
            "Released a Remotion + Claude Code demo-video workflow that resonated with the tech community on LinkedIn (31 reactions, 7 comments) - reframing creative work as a code problem",
            "Live and publicly usable at shiftbear-five.vercel.app; code open-sourced at github.com/Bobarinn/ShiftBear",
        ],
    },
    {
        "slug": "handyman-ops-desk",
        "title": "Handyman Ops Desk",
        "detail_title": "Handyman Ops Desk - n8n Multi-Agent Business Workflow",
        "short_description": "A multi-agent business workflow built in n8n Cloud that intakes handyman service requests from a Google Form, extracts structured job data with Gemini, prices the job, proposes time slots, and emails differentiated client/operations confirmations.",
        "image": "handyman-n8n.png",
        "live_url": "",
        "try_it_url": "https://forms.gle/UvDgBFBwsR35MVQe8",
        "role": "Student",
        "company": "Baylor University",
        "industry": "Workflow Automation, AI Agents, Operations",
        "technologies": ["n8n", "Google Gemini", "JavaScript", "Google Sheets", "Gmail API", "Webhooks"],
        "one_sentence_summary": "A no-code multi-agent workflow built in n8n Cloud that automates the front-office of a handyman business from form submission to client confirmation.",
        "business_problem": "Small home-services businesses lose customers in the gap between request submission and a quote or scheduling reply. The manual triage workflow (read request, estimate, schedule, reply) is slow and inconsistent, and prospective customers move on while staff are still drafting an email.",
        "key_features": [
            "Form-driven intake from a public Google Form into a watched response sheet that automatically kicks off the workflow",
            "Gemini-powered extraction of structured job data (service, urgency, address, zip) from free-text submissions",
            "Rules-based JavaScript pricing engine with catalog lookup by service, zip-aware travel cost, and a 20% rush surcharge for high-urgency jobs",
            "Live-time slot scheduling that respects customer day preferences",
            "Routing logic that sends high-priority or high-value jobs (urgency = high or estimate > $300) to operations, and standard jobs straight to a client confirmation email",
            "Differentiated Gmail templates for client confirmations vs. operations alerts so each audience gets the right message",
        ],
        "role_contribution": "Sole designer and builder. Architected the orchestrator-plus-four-agents topology, wrote every system prompt, built the JavaScript pricing logic, designed the IF-based routing, and authored the Gmail templates for both client and operations audiences.",
        "biggest_challenge": "Forcing Gemini to return strictly valid JSON. The model kept wrapping responses in markdown code fences (```json ... ```), which broke downstream JSON.parse calls and silently aborted the workflow mid-flow. Solved with strict JSON-only system prompts on every Gemini node, plus a JavaScript Clean JSON node that strips fences before parsing and surfaces a clear error path that preserves the raw model output for debugging.",
        "what_you_learned": "Agentic orchestration is more about plumbing and contracts than prompts. The hard parts are passing context cleanly between agents, taming non-deterministic outputs (JSON-only prompting plus post-parse cleanup), and choosing where rule-based logic belongs vs. where the LLM should drive. Rule-based deterministic logic (pricing, slot filtering) composes cleanly alongside generative AI (intake parsing, message drafting) in the same pipeline, and these patterns generalize to any LLM-in-workflow project.",
    },
    {
        "slug": "campus-skillswap",
        "title": "Campus SkillSwap",
        "detail_title": "Campus SkillSwap - Peer-to-Peer Student Skills Marketplace",
        "short_description": "A full-stack Django marketplace where students post skills they offer (tutoring, languages, music, fitness) and book sessions directly with peers. Auth, skill CRUD, star reviews, and a session-booking workflow.",
        "image": "campus-skillswap.png",
        "live_url": "",
        "role": "Student & Builder",
        "company": "Baylor University",
        "industry": "EdTech, Two-Sided Marketplace, Web",
        "technologies": ["Django", "Python", "SQLite", "Django Auth", "HTML/CSS", "Bootstrap"],
        "one_sentence_summary": "A full-stack Django marketplace where students post skills they can teach and other students discover, book, and review sessions directly with peers.",
        "business_problem": "Students have skills they could teach (Python, languages, music, fitness) and peers who want to learn them, but no campus-native channel exists. Existing platforms charge professional rates and target adults, so student-to-student exchange falls back to word-of-mouth and Discord, which is slow, fragmented, and trust-poor.",
        "key_features": [
            "Skill listings with category, pricing type (free or paid), contact preference, and availability status",
            "Star-rating reviews (1-5) with optional comments, enforced unique per learner per skill",
            "Session booking with proposed time, message, and explicit pending -> accepted/declined -> completed state transitions",
            "Unified dashboard that adapts to the user's current role (provider or learner) without splitting into two apps",
            "Marketing landing page with at-a-glance counters (skills posted, providers, categories) so a first-time visitor immediately understands the product",
            "Auth flows (register, login, logout) using Django's built-in auth, with a single User foreign key on each model to scope ownership cleanly",
        ],
        "role_contribution": "Sole designer and builder. Modeled all three core entities (Skill, Review, SessionRequest), wrote views, forms, and templates, integrated Django auth, designed the dashboard to adapt by role, and shipped the marketing landing page that communicates the product in seconds.",
        "biggest_challenge": "Designing a session-booking workflow that respects state transitions and stays consistent across two different views (the learner's outgoing requests and the provider's incoming requests). Solved by encoding the status field as an explicit choice list, using the same SessionRequest object on both sides, and making the dashboard adaptive to the current user's role rather than splitting the codebase into two parallel apps.",
        "what_you_learned": "How a real two-sided marketplace works underneath the polish: the mental model (listings, requests, status transitions, reviews) is what matters, and the framework (Django ORM, auth, templating) is the tool that executes it. Designing for two audiences in one codebase via role-adaptive views is far cleaner than fragmenting into separate apps. The pattern transfers directly to any other marketplace product.",
    },
    {
        "slug": "portfolio-assistant",
        "title": "Gemini Virtual Assistant",
        "detail_title": "Portfolio Virtual Assistant - Knowledge-Grounded Chatbot",
        "short_description": "A Gemini-powered virtual assistant embedded on this portfolio site. Grounded in a curated markdown knowledge base, scoped strictly to my background and projects, with per-IP rate limiting and graceful fallbacks.",
        "image": "portfolio-assistant.svg",
        "live_url": "",
        "role": "Designer & Builder",
        "company": "Personal Project",
        "industry": "AI/ML, Conversational UI, Web",
        "technologies": ["Django", "Google Gemini API", "google-genai SDK", "Vanilla JS", "RAG-lite", "Prompt Engineering"],
        "one_sentence_summary": "A knowledge-grounded AI assistant embedded on this portfolio that answers visitor questions about Ayokunmi using only a curated markdown knowledge base.",
        "business_problem": "A static portfolio expects visitors to skim and search for what they want. Recruiters and visitors with specific questions ('is he available for internships?', 'has he built anything with AI agents?') often leave without that answer, and a generic chatbot would happily invent dates, metrics, and employment history that aren't true.",
        "key_features": [
            "Curated chatbot_knowledge.md file injected into Gemini's system instruction, so the model answers only from facts authored by Ayokunmi - not from its training data",
            "Strict system prompt enforcing third-person he/him pronouns, friendly-but-professional tone, 1-3 paragraph length cap, and an explicit refusal-with-fallback for out-of-scope questions",
            "Dedicated hiring/availability rule that surfaces Summer 2026 internship search and contact email when visitors ask about opportunities",
            "Per-IP rate limiting (15 messages per minute) using Django's cache framework with time-bucketed keys, returning a 429 with a friendly message when exceeded",
            "Input validation (1000-char max, JSON parse guards, empty-message rejection) and an explicit 503 when GEMINI_API_KEY is missing, so the chat fails gracefully instead of leaking errors",
            "Vanilla-JS launcher widget (floating button, slide-in panel, suggestion chips, message bubbles) wired into the Django base template so it renders on every page without a frontend framework",
        ],
        "role_contribution": "Sole designer and builder. Wrote the system prompt, authored the markdown knowledge base, implemented the Django view with rate limiting and graceful fallbacks, designed the chat UI in vanilla JS, and tuned the guardrails (refusal patterns, hiring-question handling, persona consistency).",
        "biggest_challenge": "Preventing hallucination on a topic where the model has zero training data (a specific person). Generic LLMs cheerfully invent details when asked about an individual. Solved with a RAG-lite pattern: hand-authored markdown knowledge file injected into the system prompt, plus an explicit instruction that forces the model to refuse and redirect to email/LinkedIn whenever asked anything outside the documented scope.",
        "what_you_learned": "Practical AI design is about restraint, not capability. The system prompt, the knowledge boundary, and the refusal behavior do more for product quality than the model upgrade. The same pattern (LLM plus scoped knowledge plus rate limit plus graceful refusal) is exactly what real production AI products run, and it generalizes to any internal docs assistant, product help bot, or FAQ replacement.",
    },
    {
        "slug": "langchain-agent",
        "title": "LangChain Conversational Agent",
        "detail_title": "LangChain Conversational Agent - Coursework Foundations",
        "short_description": "A coursework project building a Gemini-backed chat agent with LangChain's create_agent API. Two iterations: a single-turn invocation and a stateful CLI loop that maintains its own conversation history.",
        "image": "langchain-agent.svg",
        "live_url": "",
        "role": "Student",
        "company": "Baylor University",
        "industry": "AI/ML, Agent Frameworks",
        "technologies": ["LangChain v1", "LangGraph", "Google Gemini 2.5 Flash", "langchain-google-genai", "Python", "python-dotenv"],
        "one_sentence_summary": "A two-iteration coursework chatbot built with LangChain v1's create_agent API, evolving from a single-shot LLM call to a stateful CLI loop with multi-turn memory.",
        "business_problem": "Coursework framing rather than a market problem. The AI Principles assignment was to build foundational fluency with LangChain's agent abstraction and Gemini integration, since these are the building blocks for the more complex agentic systems used in industry (and reused in larger projects on this portfolio).",
        "key_features": [
            "v1: single-shot agent invocation answering one user question end-to-end",
            "v2: multi-turn CLI chatbot that manually maintains conversation history across turns",
            "Gemini 2.5 Flash wired in via the langchain-google-genai integration",
            "Reusable system prompt ('clear, concise, polite, professional, safe') focused on agent mechanics rather than prompt engineering",
            "dotenv-based API key management to keep secrets out of source",
            "Graceful exit on 'bye' or 'exit' input, with try/except around reply extraction so the loop never crashes silently on an unexpected response shape",
        ],
        "role_contribution": "Sole student author. Designed the v1 to v2 progression to make the stateful-conversation pattern visible, kept scope intentionally minimal, and matched the dependency stack to what's used in the larger AI projects on this portfolio.",
        "biggest_challenge": "Managing conversational state when the agent itself is stateless per invocation. Solved by building a list-of-messages history that gets concatenated with each new user input and passed back into agent.invoke({'messages': ...}) - the canonical pattern for stateful agents in the new LangChain API. Aligning the dependency matrix (langchain, langchain-core, langgraph, langchain-google-genai) without version conflicts was a close second.",
        "what_you_learned": "When to use the agent abstraction over a direct LLM call (you reach for it as soon as you need tools or multi-step reasoning) and how to manage chat history outside the agent. The v1 to v2 progression - single-shot call evolving into a stateful loop - is exactly the mental model needed before adding tools, memory, and orchestration. Same patterns scale up to the production multi-agent work in Handyman Ops Desk and the Gemini Virtual Assistant on this portfolio.",
    },
    {
        "slug": "google-flow-video",
        "title": "AI Video Generation",
        "detail_title": "AI Video Generation with Google Flow (Veo)",
        "short_description": "A coursework exploration of Google Flow - Google's AI filmmaking tool powered by Veo - generating short cinematic clips from text and image prompts to learn the craft of directing generative video models.",
        "image": "google-flow-video.svg",
        "live_url": "",
        "role": "Student",
        "company": "Baylor University",
        "industry": "AI/ML, Generative Media, Video",
        "technologies": ["Google Flow", "Veo", "Text-to-Video", "Image-to-Video", "Prompt Engineering", "Generative AI"],
        "one_sentence_summary": "A coursework exploration of Google Flow (Veo) generating short cinematic clips from text and image prompts to learn the craft of directing generative video models.",
        "business_problem": "Coursework framing rather than a market problem. The AI Principles assignment was to build hands-on fluency with state-of-the-art generative video tooling and develop intuition for prompt-as-direction, since AI video models are rapidly entering professional creative workflows alongside generative image and text models.",
        "key_features": [
            "Generated short cinematic clips from text-only prompts using Google Flow's prompt-and-render loop",
            "Generated image-conditioned clips, using reference images to anchor subject and style",
            "Practiced director-style prompting - naming shot type, camera move, environment, mood, and subject behavior in compact phrases the model can parse",
            "Triage workflow: generate a small batch, pick the strongest clip, then re-prompt that direction with tighter constraints rather than chasing perfection on the first take",
            "Personal documentation of which prompt patterns produced reliable output and which kept failing, to build durable intuition",
        ],
        "role_contribution": "Sole student. Designed the prompts, ran the generation/triage loop, and documented the patterns that worked vs. failed for future generative-video work.",
        "biggest_challenge": "Translating cinematic intent (specific camera moves, lighting, pacing, subject identity across shots) into prompt text the model could reliably interpret. The model has real strengths and real weaknesses, and the cost of 'one more variation' is non-trivial - so the iteration discipline matters as much as the prompt itself.",
        "what_you_learned": "Generative AI assets are raw material, not deliverables. The value is in selection and combination, not the model. Director-voice prompting (naming shot type, camera move, mood, subject behavior in compact phrases) transfers to any image, video, or 3D generative tool. AI video tooling now belongs in the modern designer-builder toolkit alongside generative image and text models.",
    },
]

PROJECTS_BY_SLUG = {p["slug"]: p for p in PROJECTS}
