# Generated by Django 6.0.4 on 2026-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.CharField(help_text="Free-form, e.g. 'Feb 2025'.", max_length=40)),
                ('end_date', models.CharField(help_text="Free-form, e.g. 'Present'.", max_length=40)),
                ('bullets', models.JSONField(default=list, help_text='List of accomplishment bullets.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('detail_title', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(help_text='Short description shown on the homepage card.')),
                ('description', models.TextField(blank=True, help_text='Long-form overview shown on the detail page (used by professional projects).')),
                ('one_sentence_summary', models.CharField(blank=True, help_text='One-sentence hero subtitle. When set, the detail page renders the 8-section student layout.', max_length=400)),
                ('category', models.CharField(help_text="e.g. 'Fintech, Banking, Enterprise'.", max_length=200)),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('tools_used', models.JSONField(default=list, help_text='List of tool/tech names rendered as chips.')),
                ('challenges', models.JSONField(blank=True, default=list, help_text='Bullet list (professional layout).')),
                ('solutions', models.JSONField(blank=True, default=list, help_text='Bullet list (professional layout).')),
                ('impact', models.JSONField(blank=True, default=list, help_text='Bullet list (professional layout).')),
                ('key_features', models.JSONField(blank=True, default=list, help_text='Bullet list (student layout).')),
                ('business_problem', models.TextField(blank=True)),
                ('role_contribution', models.TextField(blank=True)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True, help_text="Rendered as 'What I Learned' on student detail pages.")),
                ('image', models.CharField(help_text='Filename inside main/static/main/images/.', max_length=200)),
                ('live_url', models.URLField(blank=True)),
                ('try_it_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(choices=[('core', 'Core Competencies'), ('languages', 'Programming Languages'), ('tools', 'Technologies & Tools')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'display_order', 'id'],
            },
        ),
    ]
